### PR TITLE
Update thirdparty

### PR DESCRIPTION
**Pull request by oyejorge**
Hi all, it's been too long.

I've been collecting changes for a while and thought you'd like them... or maybe some of them.

* scssphp 1.0.5
* elfinder 2.1.50
* ckeditor 4.13.0
* better fatal error catching
* some experimentation with atomic writes (should probably look at these changes some more before releasing)
* admin ui: remove draggability from admin toolbar and fixing it in the upper left of page

### CODE REVIEW

**Comment by juek** [comment]
Josh, nice to see you!

**Comment by juek** [comment]
Wow, quite some stuff to check out. 2 questions right away:

Do you have a working merged master?
Are there any new system requirements?

Well ... ok, it's 3 questions.
Tempting to merge everything you contribute. Does something speak against it?

**Comment by oyejorge** [comment]
Yeah, sorry about the size of this. It's not the right way, I just needed to stop sitting on the code.

> Do you have a working merged master?

Sorry again, I forgot to pull the latest changes. I'll do that now

> Are there any new system requirements?

Honestly didn't check but looking at the readme.md it's definitely not PHP 5.4+ compatible.
* scssphp is 5.6+
* elfinder is 5.4+
* error catching changes might be 7.0+ but not sure now

I might try this tool to see where it's at: https://github.com/PHPCompatibility/PHPCompatibility

FYI, here's a breakdown of php versions used in the past 3 months.

>    [5.2] => 2
>    [5.3] => 27
>    [5.4] => 45
>    [5.5] => 20
>    [5.6] => 187
>    [7.0] => 108
>    [7.1] => 161
>    [7.2] => 2060
>    [7.3] => 254
>    [7.4] => 2

> Tempting to merge everything you contribute. Does something speak against it?

Not sure how many people liked the floating admin menu but I personally found it more useful if it was more integrated in the top toolbar.

I made the new elfinder work for editing pages but it may not work for plugins that integrated the old finder (which I didn't remove yet).

**Comment by oyejorge** [comment]
Well, the PHPCompatibility tool shows the project (as it exists in this branch) being 5.4+ compatible. Not sure why scssphp says it's 5.6+

**Comment by juek** [comment]
I'm now going to check if it really works on PHP 5.4.

**Comment by Sestowner** [comment]
Everything works fine, but I personally prefer to display plugins in the "Plugins" group.

**Comment by mahotilo** [comment]
It works for me.

Some notes.
- I agree with @Sestowner about plugins that have "fallen out" of their dedicated menu item.
 - Also, with a new side menu layout, the buttons "home", "dashboard" and "search" should be permanently moved to the top menu.
- Another question, is it possible to upgrade to jQuery v2.2.4? I did it myself without problems, and now I have fewer warnings from Google about the number of vulnerabilities.

image

**Comment by juek** [comment]
Error reporting does not fully work in PHP 5.4(.4), and I would want to keep the floating/draggable Admin Menu for now, with plugins inside the plugin section. 

I will post a summary when I'm done with merging.

**Comment by juek** [comment]
For jQuery > 1.x we also have to test at least the most popular plugins.

**Comment by juek** [comment]
@mahotilo
@Sestowner 
Could you guys check if you get gallery thumbnails? I got none.

**Comment by mahotilo** [comment]
Oops! 
Really, we have a problem. I have tried many parts of the interface, but missed galleries.  I can't upload a file with a mixed name e.g. "Pieter Bruegel the Elder -Охотники в снегу.jpg", while pure Cyrillic "Кричевський Василь - Три віки - 1913.jpg" is fine.
Also, the Galleries page shows the only gallery on the site as hidden.

image

image

**Comment by Sestowner** [comment]
>  Could you guys check if you get gallery thumbnails? I got none.

> I can't upload a file with a mixed name e.g. "Pieter Bruegel the Elder -Охотники в снегу.jpg", while pure Cyrillic "Кричевський Василь - Три віки - 1913.jpg" is fine.
> Also, the Galleries page shows the only gallery on the site as hidden.

I haven't these problems.

**Comment by juek** [comment]
My gallery thumbs issue seems solved (it's not exactly the 'best' PHP 5.4.4 I've installed here, have to replace it for further tests)

@mahotilo 

> I can't upload a file with a mixed name

Don't have that issue either. Not on Linux nor on Windows hosts.

**Comment by juek** [comment]
> My gallery thumbs issue seems solved

Unfortunately not really.  Do you guys get gallery thumbs for images uploaded via (new 2.3.2) elFinder?

**Comment by mahotilo** [comment]
OK, I rechecked this filename on different TS versions. Same problem with different error processing. So it perhaps is due to local server internalization settings. In any case, I always avoid to use Cyrillic file names on for real sites:)

And after I cleared all possible caches, the new gallery on page goes to section"Visible" on Galleries Page.
And yes, I have gallery thumbs, but for only one gallery per page. (Is it intentional?)

**Comment by Sestowner** [comment]
>  Do you guys get gallery thumbs for images uploaded via (new 2.3.2) elFinder?

Yeah, I haven't thumbnails for images uploaded via new elFinder.

**Comment by mahotilo** [comment]
How did you upload the files? I used "add files" in gallery editor and drag&drop in File manager. I have thumbs.

**Comment by Sestowner** [comment]
> How did you upload the files?

"Content" -> "Uploaded Files" -> drag&drop into File manager.


> I used "add files" in gallery editor and drag&drop in File manager. I have thumbs.

This working for me too.

**Comment by oyejorge** [comment]
Looks like that merge didn't go very smoothly and there are a lot of conflicts.

@juek I'm wondering if we can undo the approval, clean up the update-thirdparty branch then merge. Were there merge conflicts showing when you approved the changes? Did you approve the changes via the "merge pull request" button here on github.com?

Also going to look at the uploader issues.

**Comment by juek** [comment]
> Looks like that merge didn't go very smoothly and there are a lot of conflicts.

For the approval: I only wanted to approve a single commit but that didnt' work. 
Everything i merged I did it manually. It should actually work - works here.

**Comment by juek** [comment]
that's the current state

[X] check for lang key to prevent undefined index notice
[X] use php's flock instead of WriteLock()
[  ] throw exception if username not set instead of trigger_error() and die()
[X] add modified time as cache buster to static files from plugins
[  ] testing more atomic save methods
[  ] use file_put_contents() + rename() method for atomic writes
[X] add HasCookies()
[  ] add fatal error debug info
[X] whitespace
[X] console.log when response does not have an action
[X] eemove default gpx_content value from ajaxReplace[]
[  ] try catch for fatal errors (php7.0+)
[  ] catch throwable instead of error
[  ] remove min-height for editable_area
[  ] call ShowError directly instead of triggering an error
[X] add PageCreated hook
[  ] call ShowError directly instead of triggering an error
[  ] toolbar fixed to top-left
[  ] track more information about fatal errors
[X] don't shrink elfinder scripts
[X] cmd should always be a string
[X] more debug info
[X] only detach message if a new message is being displayed (prevents dis…
[  ] elfinder 2.3.2
[X] scssphp 1.0.5
[X] update to ckeditor 4.13.0
[  ] add FileMatch to prevent access to gpjson files
[  ] add RewriteRule for gpjson security
[  ] insert image selected from elfinder into ckeditor

**Comment by oyejorge** [comment]
Gotcha. Are you seeing this? I'm also getting a lot of merge conflicts when I try to pull the remote master into my local master.

image

**Comment by juek** [comment]
I'll just try another clean install, but my local git says it's all fine.
Be back in 2 mins

**Comment by juek** [comment]
Ok. Current master installs and runs smoothly.

As you can see from the latest commits to the master branch, I haven't merged atomic writes, error catching, gpjson things, elFinder and the fixed Admin Menu.

I had issues with:
* error catching in PHP 5.4 (not yet investigated further)
* elFinder integration (gallery thumbs not created)

I would like to keep the floating Admin Menu for now.

**Comment by juek** [comment]
However, I don't know where the include/thirdparty/ckeditor conflicts come from, because I simply copied the whole directory.

**Comment by juek** [comment]
... so I believe, what I did is called cherry-picking. But I didn't do it with the git cherry-pick command but everything by hand, testing every change in 4 different installations and then commit -> push.

**Comment by oyejorge** [comment]
Ok, so git sees your changes as different from the changes in this branch. Essentially, the conflicts are because git sees two changes (those in this branch and yours) effecting the same lines/files.

This, of course, never would have happened had I not lumped a bunch of changes into one pull request.

It'll work as long as we're careful (which you're clearly already doing). We just won't be able to merge this pull request (which sounds like might not be a problem since we don't want all of the changes).

>  testing every change in 4 different installations

[I've been working on getting unit tests working with better code coverage](https://travis-ci.org/Typesetter/Typesetter/builds/622320298). I have tests running on 5.4, 5.5, 7.0, 7.1, 7.2 and 7.3 (I missed 5.6 somehow and there's an issue with 7.4 that will hopefully get fixed soon). It's still not a bad idea to check things manually, but as we build better coverage in the tests, we can spend less time manually re-checking.

**Comment by juek** [comment]
@oyejorge 

Maybe this helps: 

When using the update-thirdparty branch with PHP 5.4.4 and producing a fatal error, I get this msg:

```
md5_file([TS installation dir]/data/_site/fatal_exec_c6c7e6cbd5b123b53943c929bcf041aa): failed to open stream: Permission denied
    in: [TS installation dir]/include/admin/Tools/Errors.php
    on line: 85
    Request: /typesetter/index.php/Admin/Errors?
    Method: GET
    time: 2019-12-08 00:12:23 (1575763943)
    REMOTE_ADDR: ::1

```    
The directory exists. 
'Clear all erros' works, clearing a single error won't.

Permissions are ok AFAIK. Could this be a file lock issue?

**Comment by juek** [comment]
If we get gallery thumbs working, I'd love to go for elFinder 2.3.2 - although it's a bit slow, it's clearly advanced. 
But I would disable all remote image editor integration. That's the kind of stuff that rings bells in my 'security brain area'.

**Comment by juek** [comment]
One more thing would need to be fixed: elFinder 2.3.2 does not abide by Typesetter's upload extensions allow/deny rules.

**Comment by mahotilo** [comment]
I have such an error notification instead of opening the image in new window after double-clicking.
image

**Comment by Sestowner** [comment]
> I have such an error notification instead of opening the image in new window after double-clicking.

It's error happen no matter which file is double-clicked, but I fixed this. And before I'll commit, which action you guys prefer for double-click: **open** or **preview**?

**Comment by mahotilo** [comment]
It turned out to be so difficult to close "preview" that I prefer "open"

**Comment by juek** [comment]
I'd also go for 'open'. 

Preview has no close option, only minimize.
We need to hit [ESC] or click the preview icon again to close it. 
Some folks have a strange sense of UX.

**Comment by Sestowner** [comment]
> Preview has no close option, only minimize.

It has close option, but it displaying is broken by [commented 37 line in main.custom.js](https://github.com/Typesetter/Typesetter/blob/update-thirdparty/include/thirdparty/elFinder/main.custom.js#L37)
image

after uncomment the result would be like this 
image

**Comment by juek** [comment]
> Preview has no close option, only minimize.

fixed with [this commit](https://github.com/Typesetter/Typesetter/commit/bf12de31070c4dfafa9414d724bffd8ef069edfc)

**Comment by Sestowner** [comment]
@juek 
@mahotilo 
Now preview has close option, did that change your mind about action of double-click.

**Comment by juek** [comment]
> Now preview has close option, did that change your mind about action of double-click.

Hard decision. Preview might handle some media better then a raw browser window. Let's go for preview now?

**Comment by mahotilo** [comment]
Yes, despite the slightly ugly icons in the preview windows it is better than the image in the new browser window.

I vote for preview.

**Comment by juek** [comment]
> Yes, despite the slightly ugly icons in the preview windows

Using CSS to combat jQuery UI, you never really win.

@Sestowner Thx, works!

**Comment by mahotilo** [comment]
> Using CSS to combat jQuery UI, you never really win.

I rather meant this than 'close' button :)

image

@Sestowner
I can also confirm. It works.
And now I can upload my combined 'Pieter Bruegel the Elder -Охотники в снегу.jpg' without problems.

**Comment by juek** [comment]
> I rather meant this than 'close' button :)

Then never buy a Mac!

**Comment by mahotilo** [comment]
> Then never buy a Mac!

I promise I won't.
Only M$ since DOS 2.0:)

**Comment by juek** [comment]
> I promise I won't.

Good boy!  :))

**Comment by mahotilo** [comment]
I wondered how to fix buttons layout in Finder and found some problems.

We use these images in jquery-ui.min.css

> ui-bg_glass_75_dadada_1x400.png
> ui-bg_glass_75_e6e6e6_1x400.png
> ui-bg_highlight-soft_75_cccccc_1x100.png
> ui-icons_888888_256x240.png

but they are absent in jquery_ui\images. 

In fact, they are not from themes\ui-lightness but from themes\smoothness.

I discovered this while I got an error in the console. But now I can't reproduce it. But the missing files are still in .css.

**Comment by juek** [comment]
> We use these images in jquery-ui.min.css ... but they are absent in jquery_ui\images.

Yes, the pngs are missing. They have been missing for ages, and yes, that's an error. But, if you ask me, the buttons look much better without them.

But we could do our poor browsers a favor and give them some transparent pixels instead.

**Comment by juek** [comment]
grafik

OK, with the current build, there's hardly any difference anymore.

I'll add them.

**Comment by juek** [comment]
Said and [done](https://github.com/Typesetter/Typesetter/commit/f5290cbac69ada78d42411c6d6080bca2db88a67)

**Comment by mahotilo** [comment]
Or maybe I can beautify our custom jquery-ui.min.css (it does not match to any jquery-ui themes anyway) delete this backgrounds and minify it again? We will save some bytes.

**Comment by mahotilo** [comment]
Oh, slow me:)

**Comment by juek** [comment]
I post here because it doesn't matter here anyway. 
I just have to finish another project. I'll be back tonight or tomorrow.

**Comment by mahotilo** [comment]
Jürgen,
in what current state do you see this PR?
Do you think your checklist is filled?
https://github.com/Typesetter/Typesetter/pull/340#issuecomment-562978569

Do we have the tasks to do some QA tests?

**Comment by juek** [comment]
> in what current state do you see this PR?

It's not relevant is the current form anymore.

> Do you think your checklist is filled?

Yes I'm done here.

> Do we have the tasks to do some QA tests?

We will certainly still encounter some issues. 
I would be surprised if a 5.2.1 version was not necessary. It always is. Everywhere.

**Pull request closed without merging**
