### PR TITLE
Avoid additional Sections Link before Section name

### PR DESCRIPTION
**Pull request by mahotilo**
Does all this href="?cmd=ManageSections" have a sense beside being just a link for proper styling by CKE?

### CODE REVIEW

**Comment by juek** [comment]
In some languages the top bar sections link will be covered

grafik

**Comment by mahotilo** [comment]
For this situation we have such a beautiful chevron,

**Comment by mahotilo** [comment]
And it is a discrimination of 'Layout'

**Comment by mahotilo** [comment]
I have started  naming sections since recent times, and that helps me with a long one-page site very well. So I think, it is very good to clearly see the centered name of the edited section without any distraction.

Maybe, setting `min-width` for  Sections,  Extra Content,  Layout, and  Revision History can help in this situation?
Sth like this
`#admincontent_panel .panel_tabs li a {min-width: 90px}`.
But it works until is editor panel is expanded.

**Comment by mahotilo** [comment]
Or I can propose a radical solution.

```
body.gpAdmin #gp_admin_html #ckeditor_wrap{
    top: 30px;
}

```
image

**Comment by juek** [comment]
> Or I can propose a radical solution.

I thought of the same thing. Basically... yes. 

It's just that I don't want to bother too much with the current admin UI details, as I think more than that is required (including docking and some other things I would rather do after 5.2 released)

**Comment by mahotilo** [comment]
Ok.
Let it be as it is.

**Comment by juek** [comment]
But let's collect all the ideas in a separate thread, e.g. called TODO: future Admin UI ideas

**Pull request closed without merging**
