### PR TITLE
Notifications

### PR DESCRIPTION
**Pull request by oyejorge**
I kept telling myself I would just make one more change...
* Tabs in dialog instead of previous/next links
* Always sort notifications with highest priority first
* Removed GetDebugInfo() ... was it needed in a plugin?
* Reduced class complexity from [118](https://scrutinizer-ci.com/g/Typesetter/Typesetter/code-structure/master/class/gp%5Cadmin%5CNotifications) to [97](https://scrutinizer-ci.com/g/oyejorge/Typesetter/inspections/da65b801-a3fc-463d-a6d6-86feba6d9dff/code-structure/class/gp%5Cadmin%5CNotifications)

Notifications

What do you think?

### CODE REVIEW

**Comment by juek** [comment]
Oh yeah. Bought!

**Comment by oyejorge** [comment]
Awesome.

I had a couple of follow ups:
* [\gp\tool\Files::GetDrafts()](https://github.com/Typesetter/Typesetter/blame/master/include/tool/Files.php#L293) and [GetPrivatePages()](https://github.com/Typesetter/Typesetter/blame/master/include/tool/Files.php#L399) are only used by the new Notification class. Can I move those?
* [UpdateNotifications()](https://github.com/Typesetter/Typesetter/blob/master/include/admin/Notifications.php#L687) is always called with $ajax_include= true. Is the false option needed?

**Comment by juek** [comment]
> \gp\tool\Files::GetDrafts() and GetPrivatePages() are only used by the new Notification class. Can I move those?

Sure thing. If we need to call them for other purposes, we'll find them there. 

> UpdateNotifications() is always called with $ajax_include= true. Is the false option needed?

Um, er ... yes, if that's the case :)

**Comment by juek** [comment]
Seems we have a stray $notification variable in CheckNotifications()

https://github.com/Typesetter/Typesetter/blob/dccd32d33babe348b3eb6612a9087a293c4ad882/include/admin/Notifications.php#L473 and https://github.com/Typesetter/Typesetter/blob/dccd32d33babe348b3eb6612a9087a293c4ad882/include/admin/Notifications.php#L474

**Comment by juek** [comment]
Ah, ok i see &$notification. Never mind

**Pull request merged**
