### PR TITLE
Theme moono-lisa-TS[-c] for CKEditor

### PR DESCRIPTION
**Pull request by mahotilo**
Two new CKEditor themes 
moono-lisa-TS  - monochrome
moono-lisa-TS-c  - colour

+autoscale in the Image dialog preview to better simulate the image in the text

edit include/tool/Editing.php#L623 to set up theme

### CODE REVIEW

**Comment by juek** [comment]
+autoscale in the Image dialog preview to better simulate the image in the text

I believe the dialog will never simulate the real image flow accurately, neither the typography nor the real css float/flow rules applied to inline images via theme css. I consider the whole simulation rather useless and a waste of screen real estate.

**Comment by juek** [comment]
IMO hspace / vspace are ugly dinosaurs from a pre-css age. I some times wonder why CKEditor still uses such old stuff.

**Comment by mahotilo** [comment]
Yep, but I still can remember the time when it was full of sense for me:) 
At least, this autoscale allow seeing full image if its size is bigger then preview window.

**Comment by juek** [comment]
I haven't touched the moono-lisa theme itself but made all adaptions in inline_edit.css (as there have already been others for kama). 

Is your colored theme moono-lisa compatible in terms of icon sizes?

**Comment by mahotilo** [comment]
> IMO hspace / vspace are ugly dinosaurs
Agree. But I personally know a person who likes them very much and actively uses them:)

**Comment by juek** [comment]
> IMO hspace / vspace are ugly dinosaurs

You should really use margin nowadays for proper alignment with the surrounding text ;o)

**Comment by juek** [comment]
… or even add some css rules like …

```
.filetype-text img[float="left"] {
  margin:0 0.5em 0.5em 0;
}
```

**Comment by mahotilo** [comment]
> Is your colored theme moono-lisa compatible in terms of icon sizes?

They were taken from the moonocolor skin
https://ckeditor.com/cke4/addon/moonocolor

Their sizes differ from ckeditor moono-liza icons in include\thirdparty\ckeditor\plugins

**Comment by juek** [comment]
I'll give it a try…

**Comment by mahotilo** [comment]
> You should really use margin nowadays 

I do, but some people believe that typing or selecting proper style is too complicated if you have such handy inputs right next to the selected image.

**Comment by mahotilo** [comment]
And it is not just about icons. Moono-lisa dialogs are bigger and I like it

**Comment by juek** [comment]
Could look like this

grafik

**Comment by juek** [comment]
But I don't like the icons too much, especially text color and background color are hard to spot and rather misleading (bg color looks like a red table)

**Comment by juek** [comment]
> Moono-lisa dialogs are bigger and I like it

Definitely a huge improvement.

**Comment by juek** [comment]
Did you ever try [FlatAdmin 2015](https://www.typesettercms.com/Plugins/279_FlatAdmin_2015) (not compatible with Typesetter anymore, don't use it nowadays).

I believe I used moono or moono-lisa then.

**Comment by mahotilo** [comment]
>  (bg color looks like a red table)

It is true. I hate it too. 
I even thought the best option would be just added a little tint for monochrome icons based on main color of corresponding kama icons.

**Comment by juek** [comment]
> I even thought the best option would be just added a little tint for monochrome icons based on main color of corresponding kama icons.

LOL I had exactly the same idea.

**Comment by mahotilo** [comment]
> Did you ever try FlatAdmin 2015 

Yes, I did. I have used it in some project and found admin theme very cute. But, I remeber that at the time I was not very happy with monochrome:)

**Comment by juek** [comment]
We should get rid of flash BTW. The CK icon and the _uploaded/flash folder as well.

**Comment by juek** [comment]
> But, I remeber that at the time I was not very happy with monochrome:)

Sometimes beauty has to suffer. 
(OMG what have we done)

**Comment by mahotilo** [comment]
Beauty will save the world

(quote of one failed terrorist:)

**Comment by Sestowner** [comment]
> I believe I used moono or moono-lisa then.

Actually you used **minimalist**.

**Comment by juek** [comment]
grafik

Ewww.

**Comment by mahotilo** [comment]
It is nice

And it is too fast for me. I managed to make only a couple of steps with blue:)
image

**Comment by juek** [comment]
We should continue the discussion [here](https://github.com/Typesetter/Typesetter/issues/377)

**Comment by juek** [comment]
> We should get rid of flash BTW

[Rest](https://github.com/Typesetter/Typesetter/commit/db062e8d167da0d3dedbc9755d2246f366c8d88f) in <s>hell</s>peace.

**Comment by mahotilo** [comment]
> Rest in ~~hel~~l peace.

What about this?
index.php/Admin/CKEditor/Config
image

It is only for Flash, is not it?
https://ckeditor.com/docs/ckeditor4/latest/api/CKEDITOR_config.html#cfg-filebrowserFlashBrowseUrl
https://github.com/Typesetter/Typesetter/blob/d5bd66446ca0a88ab1ad9bd4c3bff126b78e765f/include/tool/Editing.php#L684

**Comment by juek** [comment]
> What about this? :)

[Removed](https://github.com/Typesetter/Typesetter/commit/d1cbe258ac9b6a1a83267a6deebac182f4aa4542)

**Pull request closed without merging**
