### PR TITLE
One more place to trigger 'editor:loaded'

### PR DESCRIPTION
**Pull request by mahotilo**
If you don't mind. It is just for the proper work of my CKE theme plugin. I can not find another justification:)

### CODE REVIEW

**Comment by juek** [comment]
Do you use the InlineEdit_Scripts hook?

**Comment by mahotilo** [comment]
No, I did not know about it.
Do you mean, I can use this hook to inject my JS to trigger event without changes to TS?
I will try this way a little later.

**Comment by juek** [comment]
> Do you mean, I can use this hook to inject my JS to trigger event without changes to TS?

I think so.

**Comment by mahotilo** [comment]
I have just made such test function (and relevant changes to `Addon.ini` as well). And you know, the alert does not fires on `/Admin/CKEditor/Example`. On other pages it works, but not on the `Example`.

```
	public static function InlineEdit_Scripts($scripts,$type){
		$scripts[] = array( 'code' => 'alert(\'type ' . $type .  ' \')' );
		return $scripts;
	}
```

**Pull request closed without merging**
