### PR TITLE
Fixes #467 without breaking #467

### LINKED ISSUE #467: Extra Content publishing error
I have such an error on the page "`http://www.test:8080/index.php/Admin/Extra?file=Bootstrap_Dropdown_Divider`" when I try to reload the page after the draft is published.

image

I have no warnings from browser about "send page content again".

UPD
Publication should be made here
image

### PR DESCRIPTION
**Pull request by oyejorge**

### CODE REVIEW

**Comment by mahotilo** [comment]
Sorry to say it.
Now it breaks https://github.com/Typesetter/Typesetter/issues/467#issuecomment-574023211 again.
The first click on the Publish button in the right panel does not give a visible result and the second one gives 'Oops'.

**Comment by oyejorge** [comment]
frick!

Fortunately (or not) this is more of a css issue where we have [display:block!important;](https://github.com/Typesetter/Typesetter/blame/cc86215c653681cc236dcf03042c22877eb4bb25/include/css/manage_sections.css#L421) conflicting with the display:none of the .nodisplay class.

FYI, the reason I went for using the nodisplay class instead of jquery's .show()/hide() method was because show() was adding a display:inline to the publish link which was messing with the sizing.

Thinking about adding something like $gp.show(elements) and $gp.hide(elements) methods

**Comment by juek** [comment]
we probably should get rid of that !important anyway

**Comment by oyejorge** [comment]
I've tried a few things and I don't think removing the !important was enough. [Take a look at my latest pull request](https://github.com/Typesetter/Typesetter/pull/504)

**Pull request merged**
