### PR TITLE
Some work on buttons in elFinder

### PR DESCRIPTION
**Pull request by mahotilo**
Fixed buttons in full view and in preview

### CODE REVIEW

**Comment by juek** [comment]
I just reverted your last pr and moved your changes to admin_finder.scss
We should keep the original distribution as untouched as possible and override things with our (s)css. 

Makes future maintenance easier.

**Comment by mahotilo** [comment]
Well, I can only agree with you. But theme.css is a legel way to make some changes. We can introduce e.g. TS theme, but we need to define it in js "options".

**Comment by juek** [comment]
There are also quite some tempting elFinder themes [out there](https://www.google.com/search?client=firefox-b-d&q=elfinder+themes)

**Comment by juek** [comment]
> But theme.css is a legel way to make some changes. 

Sure it is, but it might get replaced with an update.
Using admin_finder.scss also lets us adapt elFinder to its context (popup window / admin page)

**Comment by mahotilo** [comment]
I totally agree and have moved my focus to admin_finder.scss:)

**Pull request merged**
