### PR TITLE
Galleries isolated in colorbox

### PR DESCRIPTION
**Pull request by mahotilo**
Just if you want to try how it will be:)
Now cycling in colorbox is limited to current gallery.

### CODE REVIEW

**Comment by juek** [comment]
Sorry but it has no effect here. I have saved all (3) galleries on a page and the rel attributes per gallery differ. Maybe sth. else missing?

**Comment by juek** [comment]
Ok, seems to be a plugin interference. We will need to overwrite the rel from the attribute via $gp.cboxSettings() each time.

**Comment by mahotilo** [comment]
> Ok, seems to be a plugin interference. 

Which plugin do you suspect? I tested with cboxSettings and it works for me.

**Comment by juek** [comment]
> Which plugin do you suspect?

None you know, and it's not done too well. I push a more secure implementation short-term.

**Comment by juek** [comment]
[This commit](https://github.com/Typesetter/Typesetter/commit/f2bccecbd588fab8720141730ddb9042f21fff42) should be safe and will not break existing TS 5.1 galleries.

**Comment by mahotilo** [comment]
Yes, it works great for me. We can close the issue!

**Pull request merged**
