### PR TITLE
Update elfinder.full.js

### PR DESCRIPTION
**Pull request by mahotilo**
Fix for resizeable/modal dialogs sizing. Once again

### CODE REVIEW

**Comment by mahotilo** [comment]
Yes, it will. This is just a trick to remove the “if” without any significant reformatting of .min. version

**Comment by mahotilo** [comment]
We need this patch because its previous version is good only for the Resize&Rotate dialog (that I used to check) and breaks (сauses or blocks) scrolling in Info, Preference and TextArea dialogs.

**Comment by juek** [comment]
As Josh already mentioned, we should really try to get our direct modifications out of the elFinder core and move them to main.custom.js -> options, if possible. Further maintenance will become difficult this way.

**Comment by mahotilo** [comment]
Agree, but I didn't find away to patch this function. The only way I can see is to make PR for elFinder itself and wait until/if it will be accepted.

**Comment by mahotilo** [comment]
Ok, I've created a PR for elFinder, will see how it ended.

**Pull request merged**
