### PR TITLE
Fix gpOutput::Area saving to config(customlang)

### PR DESCRIPTION
**Pull request by mahotilo**
It is for https://github.com/Typesetter/Typesetter/issues/567

### CODE REVIEW

**Comment by mahotilo** [comment]
We still have a problem with return to the "page" 'Admin_Theme_Content/Text' which is used as the form 'action' value.

**Comment by juek** [comment]
In which use cases does this fix help?

**Comment by mahotilo** [comment]
Problem:
1. Add 
`gpOutput::Area('My_Html_Area','<div class="my_html_area">%s</div>');`
and 
`gpOutput::GetArea('My_Html_Area','This Text');`
to template
2. Edit and save `This Text`. It works
3. Try to edit and save `This Text` again. It doesn't work

The PR fixes this.

**Comment by mahotilo** [comment]
As I understand it, this part of the TS code is antique, and not Ajaxed.

**Comment by juek** [comment]
> As I understand it, this part of the TS code is antique, and not Ajaxed.

It actually should result in an AJAX response. I tracked it back to the point where 
[ReturnHeader()](https://github.com/Typesetter/Typesetter/blob/master/include/admin/Layout.php#L1669) is called, which is the case.  But I cannot see the JS response it should generate.

@oyejorge can you check this?

**Comment by juek** [comment]
But let's continue discussing it further in the [issue](https://github.com/Typesetter/Typesetter/issues/567)

**Comment by juek** [comment]
@oyejorge Alarm off! Seems like we got it all sorted.

**Comment by oyejorge** [comment]
Sounds good!

**Pull request merged**
