### PR TITLE
Prevent access to Revision History & Layout Editor when the site is locked for editing

### PR DESCRIPTION
**Pull request by Sestowner**

### CODE REVIEW

**Comment by juek** [comment]
Why do you want to block those two features, when exactly nothing will work with a locked admin state. Not a sinlge admin page, no editing at all, no settings, nothing. So why block those two?

**Comment by mahotilo** [comment]
Maybe to prevent any of such situation with iframe?
Do we already have protection against them?

https://github.com/Typesetter/Typesetter/issues/243#issuecomment-398472669

**Comment by juek** [comment]
> Do we already have protection against them?

I do not think so. But why would I want to enter Layout Editor when I know I can't do anything there? The message box clearly states that I may not edit.

**Comment by mahotilo** [comment]
I can give you a real life example. It is a bad practice, but...
1. User1 opens layout editor and works with it
2. User1 stops his work and goes out for more than 15 min.
3. User2 logs on to site (as admin as well), waits 15 min. and starts to edit some page
4. User1 returns and tries to continue his work.
5. Boom - error.

**Comment by juek** [comment]
User 1 logs in and makes some edits but doesn't publish (1). Must go out to take the kids to school.
User 2 logs on, hits 'Publish Draft' (2) and logs off again.
User 1 comes back, wants to publish (3), Boom.

Replace (1), (2) and (3) with arbitrary admin actions and it will cause hassle, more or less. It is asking for trouble.

So, before you leave, 
turn off the stove, 
save your work 
and log off. 
     (Konfuzius or Diogenes)

Come on.

**Comment by mahotilo** [comment]
My first thought. If we can hide matches from kids, why do not use it?

But...
Do not mind. I trust your vision. If you do not like such restriction of user's rights or see possible complications, let us leave all as is.

And don't forget your towel :)

**Comment by oyejorge** [comment]
>   User1 opens layout editor and works with it
    User1 stops his work and goes out for more than 15 min.
    User2 logs on to site (as admin as well), waits 15 min. and starts to edit some page
    User1 returns and tries to continue his work.
    Boom - error.

I don't think this situation changes with the suggested changes to the code.

**Comment by juek** [comment]
I just don't want to take pills that will impair [a possible cure](https://github.com/Typesetter/Typesetter/blob/master/include/languages/uk.main.inc#L742) later on.

**Comment by mahotilo** [comment]
Intrigue

**Comment by oyejorge** [comment]
@juek I'm curious. I got the impression you were leaning against merging this?

**Comment by juek** [comment]
@oyejorge 

> I got the impression you were leaning against merging this?

I was, but the iframe reloading in LayoutEditor that occurs in fast succession with a locked account may cause file corruption in very special situations on fast connections (e.g. local servers)

**Comment by juek** [comment]
@oyejorge 

As an example: our CustomSections plugin looks for section types by parsing subdirectories. When logged-in, this will be always done with every page load and cached - for normal visitor performance. This cache may be corrupted. Same will most likely also apply when debugging to files instead of messages.

**Comment by oyejorge** [comment]
Gotcha.

**Comment by Sestowner** [comment]
Sorry for the too late answer.


> Maybe to prevent any of such situation with iframe?
> [#243 (comment)](https://github.com/Typesetter/Typesetter/issues/243#issuecomment-398472669)

>  iframe reloading in LayoutEditor that occurs in fast succession with a locked account may cause file corruption in very special situations on fast connections

True. That why I made those changes.


> * User1 opens layout editor and works with it
> 
> * User1 stops his work and goes out for more than 15 min.
> 
> * User2 logs on to site (as admin as well), waits 15 min. and starts to edit some page
> 
> * User1 returns and tries to continue his work.
> 
> * Boom - error.

Sorry, suggested changes cannot prevent this situation.

**Pull request merged**
