### PR TITLE
CKEditor empty <i> tag

### PR DESCRIPTION
**Pull request by Polesz**
CKEditor do not delete the empty `<i></i>` tag.
This uses `<i class="uk-icon-home"></i> or <i class="fa fa-home"></i>`

### CODE REVIEW

**Comment by juek** [comment]
Hi Peter, 
if you want to prevent CKEditor from removing empty <i>s (or <span>s) the simplest way is to insert a so-called "zero-width non-joiner": <i class="fa fa-flag">&zwnj;</i>

**Comment by a2exfr** [comment]
I prefer to insert 
`CKEDITOR.dtd.$removeEmpty['i'] = false;`
in editor -  config.js

**Comment by juek** [comment]
> I prefer to insert
> CKEDITOR.dtd.$removeEmpty['i'] = false;
> in editor - config.js

Yes, that's the pro version. But we cannot do it without modifying CMS core files, so any update will reset it. Or can we?

**Comment by a2exfr** [comment]
>  so any update will reset it.
Yes, its true. 
I'm not sure may be it possible to use Ckeditor config options in admin part?

`config.protectedSource.push(/<i[^>]*><\/i>/g);`

**Comment by juek** [comment]
I fear the Admin's CK config JSON format doesn't allow anything like this. 
I once (in some plugin) hijacked the inline editing functions and injected some additional functions and callbacks, but I'm not comfortable about doing so. Inline editing might also change in future versions, like it did (quite a lot) in TS5, so I keep at my little &amp;zwnj; gizmo ;)

**Comment by oyejorge** [comment]
Sounds like empty <i> tags would be a helpful thing to enable but we should probably start with a new pull request that doesn't include 250+ commits.

**Pull request closed without merging**
