### PR TITLE
Add Pencil icon before layout edit link

### PR DESCRIPTION
**Pull request by mahotilo**
To make it more visible

image

### CODE REVIEW

**Comment by juek** [comment]
At the moment we mostly use icons in the context of buttons/button-like element context but I agree that it has become a bit inconsistent. FontAwesome is pixel-perfect at 14px and doesn't render too well in 13px (our admin font-size). 

If we start adding icons to all admin UI links, we will certainly face quite some issues (e.g. which icon to use for 'Restore Defaults')

**Comment by mahotilo** [comment]
Well.
The 'Edit this layout' link is currently shown rather as a table header. Honestly, I don't perceive it as a place for a click. So I decided to add this pencil. Can we find another way to emphasize the purpose of this link?

**Comment by juek** [comment]
>  I don't perceive it as a place for a click.

Almost everything is a link here. Emphasizing everything counteracts emphasis by definition ;)

**Comment by mahotilo** [comment]
> Almost everything is a link here.

Yep. But how can I guess about this? 
Edit this layout just tells me: "Click on this fold/unfold buttons and edit something" :)

image

**Comment by juek** [comment]
> But how can I guess about this

Honestly, on admin pages I'd generally assume that all elements have some sort of functionality.

**Comment by mahotilo** [comment]
Er... Ok.
I give up.

**Pull request closed without merging**
