### PR TITLE
typos

### PR DESCRIPTION
**Pull request by mahotilo**
+ scroll to section on click instead on hover

It also will be great to add at the end of this list the whatsnews from previous releases. This will make it ease to find and learn new features. What do you think?

### CODE REVIEW

**Comment by juek** [comment]
> … the whatsnews from previous releases

If we only had that.

We have e.g. [this forum post](https://www.typesettercms.com/Forum?show=t2424&postid=10286%23post_10286) for 5.1 and rather brief [release notes](https://github.com/Typesetter/Typesetter/releases). Documentation has never been our strongest point.

**Comment by mahotilo** [comment]
> Documentation has never been our strongest point.

Yep, who needs it at all? :)

**Comment by juek** [comment]
> Yep, who needs it at all? :)

I firmly believe we lose many users for that reason. Seriously.

**Comment by mahotilo** [comment]
Seriously.
This is true, but we are not unique in this problem.

**Comment by mahotilo** [comment]
I've made such add to typesettercms.com Documentation.
https://www.typesettercms.com/Docs/Plugins/HTML_Head

Do you know other events besides 'resize', etc?
And place for this add is not ideal, but I have not found a proper one.
What do you think of Wiki on https://github.com/Typesetter/Typesetter as a sandbox for draft Documentation?

**Comment by juek** [comment]
> Do you know other events besides 'resize', etc?

editor_area:loaded is missing. 
For generic JS events like resize, click etc. (even namespaced ones like click.cbox) I think we do not need to document them.

**Pull request merged**
