### PR TITLE
Fix wrong bracket

### PR DESCRIPTION
**Pull request by Sestowner**

### CODE REVIEW

**Comment by juek** [comment]
Thx. 
FYI: Child Thumbnails will not automatically be updated on typesettercms.com. 
It would be up to Josh to do this.

**Comment by juek** [comment]
... and (another FYI)
addons with -- prefixed folders will not be part of a release.

**Comment by Sestowner** [comment]
> ... and (another FYI)
> addons with -- prefixed folders will not be part of a release.

off-topic: what do you think about moving them to own repositories or another repository?

**Comment by juek** [comment]
I don't know if Josh will still support the plugins, don't think so. So the simple answer is Yes.
Im not sure if i have sufficient permissions to move them.

For --Plugin_Examples, --Notifications-Example, --Highlight_Search_Results, --AvailableClasses and --ReplaceContentVars, they're merely for developers to illustrate plugin hooks or other functionality. 
I'd keep them in the master branch.

**Pull request merged**
