### PR TITLE
Underscore to space in Admin Link

### PR DESCRIPTION
**Pull request by mahotilo**
For better UX

### CODE REVIEW

**Comment by juek** [comment]
Where will it apply?

**Comment by mahotilo** [comment]
image
image

**Comment by juek** [comment]
I believe it's a current CustomSections issue.

Screenshot (without your patch):
grafik

**Comment by juek** [comment]
Are you sure that you have all the recent commits?
It appears as if you don't see the actual Admin Link **Label** but the slug conponent. 

With SimpleBlog, it shouldn't read 'Admin_BlogConfig' but 'Admin Blog Configuration'

**Comment by mahotilo** [comment]
Well.
It is a picture from the last master without any patches and with only Simple Blog plugin.
I can see both `Admin_BlogConfig` and `Admin Blog Configuration`

image

**Comment by mahotilo** [comment]
Yes, now I see. There is no need for my "patch". It only cures symptoms, but not the problem itself.

**Comment by mahotilo** [comment]
Source is here https://github.com/Typesetter/Typesetter/blob/f52a4a8bd2c5de0df7c4b6a4ed303e4a735da2f1/include/admin/Tools.php#L319-L334

If I comment this new lines, admin links for plugins from `/data/_addoncode ` are processed correctly.
But plugins from `/addons` are still processed wrongly (function name instead of label).

**Comment by mahotilo** [comment]
Exactly here. One line overwrites previous.

https://github.com/Typesetter/Typesetter/blob/f52a4a8bd2c5de0df7c4b6a4ed303e4a735da2f1/include/admin/Tools.php#L323-L324

**Comment by mahotilo** [comment]
I don't have a clue what sense has all this lines 320-334

**Comment by mahotilo** [comment]
I have just created the Issue https://github.com/Typesetter/Typesetter/issues/488, so I closed this PR

**Pull request closed without merging**
