### PR TITLE
Minify JS cache

### PR DESCRIPTION
**Pull request by mahotilo**
It minifies `combined_*.js` in data/_cache

Add **tedivm/JShrink** Javascript Minifier built in PHP (http://www.tedivm.com) to `/thirdparty`
Call `\JShrink\Minifier::minify()` in `tool/Output/Combine.php `

Result - 10-15% reduced size of `combined_*.js` and 10% of gziped `combined_*.js`
Minification do need some time.
Sorry, I can't estimate additional memory  resources it needs.
But PageSpeed Insights is happy and I am too.

### CODE REVIEW

**Comment by juek** [comment]
I have to test memory consumption and capabilities it with some larger js libs/scripts. 
We might need to implement a switch for it in Settings->Configuration or at least in gpconfig.
But it looks good at a first glance.

**Comment by mahotilo** [comment]
> We might need to implement a switch for it in Settings->Configuration or at least in gpconfig.

I was going to ask you about it. My skill still is't enough for this:)

**Comment by juek** [comment]
It's in with [this](https://github.com/Typesetter/Typesetter/commit/c5acd8048912f1c6cc5535fbd833aa7001605f1a) and [this](https://github.com/Typesetter/Typesetter/commit/758753816fc09bf9fd48067aab979ddbc15a768e) commit.

Currently, existing JS caches will only get minified after switching minifyjs on AND the JS cache needs to be rebuilt. It it already exists, it won't get touched. I have yet to figure out how to change that.

**Comment by mahotilo** [comment]
Tried it. Works like a charm.
I used my raw patch on two sites  with active editing during 5 months. Have seen no problem with minified scripts. So hope we will see no one and in the wild:)

> I have yet to figure out how to change that.
I looked into all chain from GenerateFile() to GetHead_JS() and also failed to force JS cash update. It is not so easy.

**Pull request merged**
