### PR TITLE
Update uk.main.inc

### PR DESCRIPTION
**Pull request by mahotilo**
Trying to make this option more understandable + small fixes

@Sestowner
Sergiy, what do you think of this?

### CODE REVIEW

**Comment by mahotilo** [comment]
@juek
~~Houston~~ Jurgen we have a problem
Last greate PR from @Sestowner was overwritten with [this commit](https://github.com/Typesetter/Typesetter/commit/a8186bda40a28d9759df94d35c14c06c736b927a)

**Comment by juek** [comment]
> Last great PR from @Sestowner was overwritten with this commit

Opps, I just [fixed it](https://github.com/Typesetter/Typesetter/commit/542fa97d1372449481ee09b2399c864fa7bc07bc).

**Comment by mahotilo** [comment]
Thx!

And my PR is still relevant.

**Comment by juek** [comment]
Ok, everything should be in sync again

**Comment by mahotilo** [comment]
No, we still have a bit of a mess.
It is better to exclude my last PR and apply the last one from @Sestowner.
I will rather do another one.

**Comment by mahotilo** [comment]
All should be fixed with this PR https://github.com/Typesetter/Typesetter/pull/476

**Pull request merged**
