### PR TITLE
Font Awesome 5 support

### PR DESCRIPTION
**Pull request by mahotilo**
Add Font Awesome 5 support. Tested on one BS4 theme. Looks like no conflicts with internal use of FA4

### CODE REVIEW

**Comment by mahotilo** [comment]
I didn't test CDN, sorry

**Comment by juek** [comment]
There are several points speaking against bundling FontAwesome 5 with Typesetter:

- FontAwesome 5.x is quite different than 4.x. Unfortunately it partially uses the same fa- namespace/class names, which is a bad decision in my POV because it lead to conflicts.
- The JS/SVG migration Shim is not an option IMO. And we definitely do *not* want any defer script loading and DOM manipulation trickery for *anything* in the Admin UI. 
- As you already noticed, content editing will also have issues.
- AFAIK there yet is no FA5 supporting CKEditor plugin (but [CKAwesome](https://github.com/brstuff/ckawesome) is rather new and will hopefully support FA5 soon. Not much info about it :/)

Therefore I currenly disapprove adding FontAweseome 5 as Typesetter component.

**Comment by mahotilo** [comment]
Ok, it is only proposition with very rough implementation.
But we need to adopt changes in leading tools. Problem is how to keep TS rock stability.

Currently I make project based on last TS with binded FA5. Many problems appears but as for now I can deal with it by simple adding to FA4 classes same classes from FA5. And I wonder how robust TS is. It can adopt changes easily.

**Comment by gtbu** [comment]
There is 
1. another Font - Awsome with jquery - select :  ckawsome) with FA 4 from CDN -- and 
2 another FA 4.3 at https://ckeditor.com/cke4/addon/fontawesome (just not Version 5 which is premium)
-- One point is the dependency of plugins of the respective(!) ckeditor-version(above 4.35)
-- the other is  the  empty-span -problem.  :::  <script>CKEDITOR.dtd.$removeEmpty['span'] = false;</script> ) (https://docs.ckeditor.com/ckeditor4/latest/api/CKEDITOR_dtd.html)  - for js-embedding 

I also work in this area for materialize icons and bootstrap-glyphicons and see no real problems with the above background.

**Comment by juek** [comment]
> ckawsome

Already mentioned ckawesome in my post from Apr 12 (see above)

> https://ckeditor.com/cke4/addon/fontawesome 

We already use this plugin in the [FontAwesome Typesetter plugin](https://www.typesettercms.com/Plugins/274_FontAwesome).

> One point is the dependency of plugins of the respective(!) ckeditor-version(above 4.35)

Current Typesetter plugin still works with 4.5.7 w/o errors.

>  the other is the empty-span -problem. ::: <script>CKEDITOR.dtd.$removeEmpty['span'] = false;

I addressed it with a &zwnj; adding mod in the FontAwesome Typesetter plugin, but included the CKEDITOR.dtd solution in [CKEditor-Glyphicons](https://github.com/juek/CKEditor-Glyphicons/blob/master/CKE_Glyphicons.php#L41), which is better.

**Comment by juek** [comment]
> [...] and see no real problems with the above background.

WHat do you mean with above background?

**Comment by gtbu** [comment]
I had read that 'all checks had failed' - the background was  <script>CKEDITOR.dtd.$removeEmpty['span'] = false; ----------------------
But the patch of a plugin which functions with 4.5.7 does not mean that another plugin, which uses the same plugin, functions with such an old version - so it should be better to update the plugins to the ckeditor-version. 
Hm - as You are just here : Do You plan an update of Your fontawsome 4.3 ( the CDN free all.js is nearly 700 kb.. - and i found a fontawsome font with 400 700 etc. - and lots of fontpicker plugins at github and at https://www.jqueryscript.net/tags.php?/icon%20picker/ 
So stays a lot to play...

**Comment by juek** [comment]
The 'All checks have failed' message seems to derive from a Travis misconfiguration for PHP 7.0. Nothing to worry about.

> Hm - as You are just here : Do You plan an update of Your fontawsome 4.3 ?

Next version will be FontAwesome 4.7, probably with ckawesome. 
But its currently not one of the top prioprity things to do.

**Comment by gtbu** [comment]
My first FA5 plugin is in the repository - i look for testers ...

**Comment by juek** [comment]
> My first FA5 plugin is in the repository - i look for testers ...

Great! Here's some feedback:

**General**

- The Plugin is named "Font Awsome 5 Icons" - Awesome without e. Not a real problem, though.
- Best prectice to generate the plugin ZIP archive would be to place all the code in a folder in the archive, e.g. called 'Fawesome5'. Although remote installation also works the current way, manual installation will be easier with the top-level folder included.
- The file extension md stands for <a href="https://en.wikipedia.org/wiki/Markdown">Markdown</a> and one would expect Mardown syntax in here. While Markdown also understands HTML tags, the .html extension would be appropriate. 

**Addon.ini**

- Repeated occurences of same keys (the InlineEdit_Scripts hook in our case) will not work. Only the latter definition will be registered. Therefore Typesetter plugin hooks may only registered once per addon.
- The ini file format doesn't allow line breaks in values, therefore the About text value is invalid and doesn't show up.

**Asset loading/Font Files**

I believe
$page->css_user[] =  $addonRelativeCode . '/ckawsome5/resources/fontawesome-all.css'; 
will load all required font files, so 
$page->css_user[] =  $addonRelativeCode . '/ckawsome5/webfonts/fa-brands.css'; 
$page->css_user[] =  $addonRelativeCode . '/ckawsome5/webfonts/fa-regular.css';  
$page->css_user[] =  $addonRelativeCode . '/ckawsome5/webfonts/fa-solid.css';   
could probably be omitted (?, not tested)

The custon webfont kit in /ckawsome5/_webfontkit seems to be a latin subset and therefore doesn't contain glyphs (icons), because they all reside in a high unicode range which is not part of the subset. Therefore loading 
$page->css_user[] =  $addonRelativeCode . '/ckawsome5/_webfontkit/all.css';
will do nothing at best or might even cause issues in some browsers.

I can't see any reference to /ckawesome5/fa5.css, so it's likely obsolete as well.

In /ckawesome5/dialogs/ckawesome5[-min].js I see jQuery references '$' and 'jQuery'. Not a problem but should be normalized.


Appearance/UX:

- As expected, due to conflics in the versions, loading FA5 will mess with some of Typesetter's (FA4) Admin UI icons like fa-pencil, fa-file-text-o, fa-css3 …
- CRUCIAL: The 'Select Font Awsome 5' dropdown in the plugin dialog cannot be used - it immediately hides after clicking it (at least on current Firefox/Windows here). Have not yet checked for the reason.

**Comment by gtbu** [comment]
**The "Select Font Awsome 5"-dropdow**n has the same code as in ckawsome (and in material). It is a bit fiddely in Edge and needs a longer click - and You must evtl. go down a bit with the mousepointer after the klick. It also allows the input of the first letters of an icon (it needs a codepiece to let it stand longer).
It functions on my installations (Ffox, edge) without any problems - but i will re-check it of course (i hope it is not some javascript blocker). 
**The malfunction** can also have another reason : fontawsome.com is ofter very slow and sometimes unreachable from 10 to 16 PM. In the plugin.js is a css which is loaded from use.fontawsome.com. If  it is not  loaded, then the dropdown will not appear. 

In version 0.6 i will  load the css thanks to :  var ckpath = CKEDITOR.plugins.getPath('ckawsome5');
 from a local directory.  This code is very critical :     	editor.awsome5Path = config.awsome5Path ? config.awsome5Path : 'https://use.fontawesome.com/releases/v5.0.13/css/all.css'; 	if the replace the weblink  with http://fontawesome-cdn.fonticons.netdna-cdn.com/releases/v5.0.13/css/all.css - it gives an error that it cannot load - the same is from a local directory of my website

 (A solution for users of FA 4.7 could be to edit the FA5 fonts with a professional tool and to remove the critical glyphs...: bad idea !) Another possibility may be to exclude the conflicting unicode range in the font family declarations

**Comment by juek** [comment]
select2.full.min.css is missing. I added it to /ckawsome5/resources/select2 and the dropdown seems to work

**Comment by gtbu** [comment]
Thank You - i corrected the zip in the web - but in my cases it functioned without it. Version 0.6 with local all.css will come out tomorrow. It replaces the webpath with  ckpath + 'resources/v5.0.13-all.css'. The css is already there.

**Comment by juek** [comment]
> The $page->css_user[] = $addonRelativeCode . '/ckawsome5/_webfontkit/all.css'; points to a font-version generated at fontsquirrel, which is very **much smaller** and has different font-families with '-' instead of ' _ '. I should eventually rename the classes . It is for use in text only.

It is much smaller because there are no icons in it. A latin subset won't contain any glyphs from high unicode ranges, where FA icons reside.

**Comment by mahotilo** [comment]
I have reported it on plugin forum, but if we discuss it here... I can't install it on local test server. Several tries finished with same result.

> Oops, the downloaded package could not be verified. Please try again later. 
> (Package Checksum 0c9dddb12709e96d661355934817dde1 != Expected Checksum b77a1bca8887920baab16c68b588c4eb)

Other plugins installing normally.

**Comment by gtbu** [comment]
The plugin is since yesterday in a subdirectory in the zip. The other possibility in Your case is to unzip it into the addons directory and then to look into the 'availible fonts'. You can also try xampp 7 https://www.apachefriends.org/xampp-files/7.1.18/xampp-win32-7.1.18-0-VC14-installer.exe as local server, which i use without problems.

**Comment by juek** [comment]
> I can't install it on local test server

Installs here on local and remote servers (tested PHP 5.3 to 7.1), so it's probably already solved(?)

**Comment by mahotilo** [comment]
1. Yes, I have installed plugin via direct download from typesettercms.com, but still can't do it from CMS. Maybe it due to cache.
2. After install I found regression in CMS interface. It looks like conflict with FA4
image
3. I can't find a way to edit inserted icon like it is possble with Fontawesome(4) plugin

**Comment by gtbu** [comment]
After successful installation You go to settings -> ckeditor : The ckeditor  icon is F5 . If it is not available, the  it is probably not a conflict wit FA4 but something with Your CMS . You should then install Xampp portable with a fresh cms - which local CMS do use You at the moment ?

**Comment by mahotilo** [comment]
No, I see F5 and can insert icon. But how to edit it after?

**Comment by gtbu** [comment]
After the icon is there You click at 'source' in ckeditor and edit the code

**Comment by mahotilo** [comment]
> After the icon is there You click at 'source' in ckeditor and edit the code

In @juek FontAwesome 1.2.1 we have more convenient way to edit icon. I believe you can use it for inspiration (of course, with appropriate reference to the source :) 

> The ckeditor icon is F5 . Your marked icon is 'content' - which may have a conflict (the same is on my local cms)

I have same problem after including of FA5 directly into thirdparty tools.

**Comment by mahotilo** [comment]
> It is note quite easy to make a scrollable grid as in 1.2.1 

No, I try to say not about inserting icon to text, but about editing. For example, I inserted icon, looked at it and then will to add double size and rotation. Can I doubleclick icon to do this via plugin interface?

**Comment by juek** [comment]
> … can do this patch ; another solution is to style the CMS with a different free iconset and to implement a css-Styleswitcher

FontAwesome is not only part of Typesetter's core Admin UI but also a [loadable component](https://github.com/Typesetter/Typesetter/blob/439e91970e147d529dc14ec0b9266fb8a7b4b2d3/include/tool.php#L877) (locally or from CDN) for some years now. Several themes and plugins are using it (besides the FontAwesome CKE plugin see e.g. [here](https://www.typesettercms.com/Plugins/302_Simple_Button) and [here](https://github.com/Typesetter/Typesetter/blob/1289acda9a23514bee4c6521b5d1d47936260cce/themes/Cajon_Scss/assets/php/theme.php#L14) and of course there are many existing web projects relying on it. So, it's similar to other situations where replacing/overwriting core components with incompatible (newer) versions will break dependencies and we have to carefully weigh pros vs. cons of doing so. 

Unfortunately, the FontAwesome team decided to change parts of the architecture while keeping the same css class names. From my point of view, the only thing we could currently do is to create sort of a 'FontAwesome migrate' package that resolves legacy dependencies by remapping certain icons and class names. While this could be done, it would be another component needing to be maintained.

From the legal view, the [OFL license](http://scripts.sil.org/cms/scripts/page.php?site_id=nrsi&id=OFL#8e6f58a5) requires renaming/rebranding of possibly required derivates, in case we decide to go such a route.

**Comment by juek** [comment]
> I try to say not about inserting icon to text, but about editing. 

This is what the current FontAwesome 4 CK Editos plugin uses the widget and lineutils components for, which allow to make FA icons editable instances.

**Comment by juek** [comment]
@mahotilo FA became quite complex (some might call it 'bloated') as of ver. 5. We have a similar situation as with Bootstrap 3 -> 4 (as we're currently [discussing it](https://github.com/Typesetter/Typesetter/issues/244#issuecomment-399548390)). IMO from a certain level of complexity, graphical UIs start losing convenience. The Bootstrap 4 Preset, if we decide to add all new flex, sizing and spacing stuff, will become hefty.

**Comment by mahotilo** [comment]
Of course, we need to keep balance between support of new technologies and CMS UI convenience. An experienced user can always go to page source or manually insert classes. I do believe that we don't need a full list of BS3 or BS4 classes in "Manage Classes". Even the BS3 classes list is huge. Personally, I always use Default preset and therefore want  it to be compatible with BS4.
I also think that we need to warn the user about еру complete reset of his custom classes list after clicking the "Preset..." button.

**Comment by juek** [comment]
> … we need to warn the user …

Probably yes, and we'll also have to translate it ;o)

**Comment by mahotilo** [comment]
But, FA5 and BS4 give us new powerful tools for creating modern sites. Therefore, we need to find a way to include them. 
As for FA5, this may be the best way to incorporate it as a CKeditor plugin until FA5 significantly displaces FA4. But we should not allow it to spoil the interface

**Comment by gtbu** [comment]
I do not quite understand the quetion put to me . I solved the conflict with the CMS by 
changing line 3200 of the fontawsome-all.css which maps the fa-class of FA5 
.fa,  /deleted
.fas {   font-family: 'Font Awesome 5 Free'   font-weight: 900; }
This disables FA
**The other question is icon** editing which is quite comfortabel 
1st line chooses iconfamily
2nd line styles like 2x  4x
3 line data transform (optional) as line 4
line 5 and 6 size and color

**Comment by juek** [comment]
> The other question is icon editing

@mahotilo points to the ability of the FA4 CKE plugin to doubleclick an icon when editing, which will pop up the dialog with the current icon properties loaded. Makes changes easy. CKawesome doesn't support that and IMO it would require quite some mods to achieve a similar behavior.

**Comment by juek** [comment]
I still consider a full FontAwesome 5 implementation in Typesetter too bloated (13.4 MB in total). Should be done via plugin or theme.

**Comment by juek** [comment]
[This one](https://github.com/juek/LineAwesomeCKE) will hopefully alleviate a bit the pain caused by not including Font Awesome 5 to Typesetter core.

**Pull request closed without merging**
