### PR TITLE
Fix edit for big top image

### PR DESCRIPTION
**Pull request by mahotilo**
Fix for https://github.com/Typesetter/Typesetter/issues/551
This works, but may not be the right solution.

### CODE REVIEW

**Comment by juek** [comment]
I think 'editable_area' should not be inserted by default. 
We don't have this class in non-admin page output.

**Comment by mahotilo** [comment]
> We don't have this class in non-admin page output.

Is this also admin?

image

**Comment by mahotilo** [comment]
Sorry.
Got it!

**Comment by mahotilo** [comment]
Ok. The good news is that now we (or just me) know that Edit menu is not shown due to the lack of 
'editable_area'.

**Comment by mahotilo** [comment]
This PR https://github.com/Typesetter/Typesetter/pull/550 has the same problem.

**Pull request closed without merging**
