### PR TITLE
Links for Docs and Wiki

### PR DESCRIPTION
**Pull request by mahotilo**

### CODE REVIEW

**Comment by juek** [comment]
Right now, I'm not sure the GitHub wiki isn't too restricted.

**Comment by juek** [comment]
BTW: Do you get a notification everytime a wiki page is edited? This would mean a lot of messages recently.

**Comment by mahotilo** [comment]
IMO

Download from typesettercms.com - stable official version
Docs on typesettercms.com - stable official version

Github Typesetter - cutting edge version
Github Wiki - the same for docs. Maybe a sandbox for Docs

**Comment by mahotilo** [comment]
> BTW: Do you get a notification everytime a wiki page is edited? This would mean a lot of messages recently.

Yes.

**Comment by juek** [comment]
> And we have no "merge" procedure for wiki editing

Everyone can edit. I set it up that way.

**Comment by mahotilo** [comment]
>  I set it up that way.

Now it is OK, but later it would be better to set up moderation.

**Comment by juek** [comment]
Could you please make a wiki edit so I can see how such a notification looks like and if one can unsubscribe them?

**Comment by juek** [comment]
> Now it is OK, but later it would be better to set up moderation.

Maybe. I don't really expect too many third party contributions,

**Comment by mahotilo** [comment]
Done

**Comment by mahotilo** [comment]
> I don't really expect too many third party contributions,

What about vandals, curious, and bad English? :)

**Comment by juek** [comment]
> What about vandals, curious, and bad English? :)

Well, that would lead to what's called an Edit War on Wikipedia :) 

> Done

Hmm, I didn't get a wiki change notifications.

**Comment by mahotilo** [comment]
I made another modification yesterday
image

**Comment by mahotilo** [comment]
My recent link is **bold**

image

**Comment by juek** [comment]
Ok, I got no notifications about edits - which is fine. 
Maybe only if new pages are created.

**Comment by mahotilo** [comment]
Do you have a notification about new page https://github.com/Typesetter/Typesetter/wiki/Notification-test?

**Comment by juek** [comment]
> Do you have a notification about new page

Nope. Perhaps I need to sign out. 

Signing out :) ....

**Comment by mahotilo** [comment]
I have just deleted test page. Should also be notified.

**Comment by juek** [comment]
> I have just deleted test page. Should also be notified.

Nope. 
I am surprised, however, that you get notifications. 
Can't find no special settings for that.  

But I don't really care :)

**Comment by mahotilo** [comment]
> But I don't really care :)

It disturbs me. I should create an Issue to inform you and maybe discuss the modification, if I make it.

**Comment by mahotilo** [comment]
Juergen, 
Sorry, I misled you. I have just realized, that I have no wiki modification notifications on GitHub. I have it as an RSS feed.

I usually use my Opera News to keep track of all notifications in one place. And I have separate channels for common GitHub notifications and for interesting projects on GitHub. Thus, I have no messages from GitHub Notifications tool about changes in Wiki, but I have messages from Typesetter page RSS.

**Comment by juek** [comment]
> I have it as an RSS feed

That of course sheds some light on the matter! ;)

**Pull request merged**
