### PR TITLE
Pin modal dialog to screen

### PR DESCRIPTION
**Pull request by mahotilo**
It is for https://github.com/Typesetter/Typesetter/issues/521
I've made it similar to #gp_admin_box.
But, I do not know how it will influence #gp_admin_boxc.iframe

### CODE REVIEW

**Comment by oyejorge** [comment]
This messes with the close button (admin_box_close) in the top right of the modal. What about  position:fixed on #gp_admin_box ?

**Comment by juek** [comment]
> What about position:fixed on #gp_admin_box ?

Like [this](https://github.com/juek/ExpandableEditor/blob/master/ExpandableEditor.css#L60)?

**Comment by mahotilo** [comment]
> Like this?

Adding this class solves my problem.

**Comment by mahotilo** [comment]
Because of https://github.com/Typesetter/Typesetter/issues/521#issuecomment-575899412

**Pull request closed without merging**
