### PR TITLE
CKE Example: Proper and more safe place to trigger JS event

### PR DESCRIPTION
**Pull request by mahotilo**

### CODE REVIEW

**Comment by mahotilo** [comment]
All other ways to insert JS trigger code by hooks works for all pages of the site. 
This path works more precise and does not bloat other pages. It is also quite logical, we need to fire 'editor:loaded' event as the Example page has CKE.

**Comment by juek** [comment]
No that's not a real loaded event. The CKEDITOR instance is (most likely) not yet ready on domready. 

I just did it [this way](https://github.com/Typesetter/Typesetter/commit/a971b3f7ff4ce9ed68e139febd7c388fe1941f19)

**Comment by mahotilo** [comment]
Thx.
I will try it.
Currently, I had to check CKEDITOR.on('instanceReady') inside of $(document).on('editor:loaded'). With this commit, everything should be much easier.

**Comment by mahotilo** [comment]
It works like Swiss watch.
Guys who love alternative CKE themes are grateful to you.

**Pull request closed without merging**
