### PR TITLE
Notifications

### PR DESCRIPTION
**Pull request by oyejorge**
The last set of changes 
* moves GetPrivatePages() and GetDrafts()
* remove param from UpdateNotifications()
* create Notifications::Add()

### CODE REVIEW

**Comment by juek** [comment]
Hmm, will ids be safe as query param without hashing?

**Comment by oyejorge** [comment]
Right... I will fix that...

**Comment by oyejorge** [comment]
Soo... a few more changes than just the ids. I ended up making a design change I hope you're ok with ... cool it's merged!

**Comment by juek** [comment]
> I ended up making a design change I hope you're ok with …

Sure, of course!

**Comment by juek** [comment]
Awesome!

```
public function Add( $title, $items, $bg, $color = '#fff'){
   …
}
```

I totally forgot about that. Will definitely come in handy!

**Comment by juek** [comment]
[// should we create an id?](https://github.com/Typesetter/Typesetter/blob/master/include/admin/Notifications.php#L465)

We could hash over all params. Should work.

**Pull request merged**
